print("Salom")
print("Yangi qator")
print("world qator")
print("Assalomu alaykum")
print("Assalomu alaykum")
print("Assalomu alaykum")
print("Assalomu alaykum")
print("Assalomu alaykum")
print("Assalomu alaykum")
